foreground              #FFFFFF
background              #2A1A19
selection_foreground    #2A1A19
selection_background    #FFFFFF
cursor                  #FED7A6
cursor_text_color       #060708

active_tab_foreground     #2A1A19
active_tab_background     #D89879
inactive_tab_foreground   #D89879
inactive_tab_background   #2A1A19

# black
color0      #522B29
color8      #8F5A57

# red
color1      #FFE8CC
color9      #F0D1AA

# green
color2      #FFD8CC
color10     #F0BAAA

# yellow
color3      #FFDDCC
color11     #F0C1AA

# blue
color4      #E69E9A
color12     #E69E9A

# magenta
color5      #E6AB9A
color13     #E6AB9A

# cyan
color6      #E6B29A
color14     #E6B29A

# white
color7      #FFE8CC
color15     #F0D1AA
