[mgr]
cwd = { fg = "#94e2d5" }

find_keyword  = { fg = "#f9e2af", italic = true }
find_position = { fg = "#f5c2e7", bg = "reset", italic = true }

marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked   = { fg = "#94e2d5", bg = "#94e2d5" }
marker_selected = { fg = "#cba6f7", bg = "#cba6f7" }

count_copied   = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut      = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#cba6f7" }

border_symbol = "│"
border_style  = { fg = "#7f849c" }

[tabs]
active   = { fg = "#1e1e2e", bg = "#cdd6f4", bold = true }
inactive = { fg = "#cdd6f4", bg = "#45475a" }

[mode]
normal_main = { fg = "#1e1e2e", bg = "#cba6f7", bold = true }
normal_alt  = { fg = "#cba6f7", bg = "#313244" }

select_main = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
select_alt  = { fg = "#a6e3a1", bg = "#313244" }

unset_main  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt   = { fg = "#f2cdcd", bg = "#313244" }

[status]
separator_open  = ""
separator_close = ""

[pick]
border   = { fg = "#cba6f7" }
active   = { fg = "#f5c2e7", bold = true }
inactive = { fg = "#cdd6f4" }

[input]
border   = { fg = "#cba6f7" }
title    = {}
value    = {}
selected = { reversed = true }

[completion]
border = { fg = "#cba6f7" }
